blueprint:
  name: ROBB SMARRT Draadloze Afstandsbediening knop
  description: Blueprint voor een enkele knop op de ROBB SMARRT zigbee afstandsbediening (ROB_200-024-0) voor het bedienen van een lamp. De lamp kan in en uitgeschakeld worden en met lang indrukken wordt de helderheid aangepast.
  domain: automation
  input:
    remote:
      name: Remote
      description: The remote control.
      selector:
        device:
          integration: zha
          model: ROB_200-024-0
    light1:
      name: Light 1
      description: Light controlled by button 1.
      selector:
        entity:
          domain: light
    light2:
      name: Light 2
      description: Light controlled by button 2.
      selector:
        entity:
          domain: light
    light3:
      name: Light 3
      description: Light controlled by button 3.
      selector:
        entity:
          domain: light
    light4:
      name: Light 4
      description: Light controlled by button 4.
      selector:
        entity:
          domain: light
    scene1:
      name: Action for Scene 1
      description: Action for S1 button
      selector:
        action: {}
    scene2:
      name: Action for Scene 2
      description: Action for S1 button
      selector:
        action: {}
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.entpoint_id == 1 }}"
                sequence:
                  - service: light.turn_on
                    data: 
                      transition: 0.2
                    target:
                      entity_id: !input light1
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.entpoint_id == 2 }}"
                sequence:
                  - service: light.turn_on
                    data: 
                      transition: 0.2
                    target:
                      entity_id: !input light2
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.entpoint_id == 3 }}"
                sequence:
                  - service: light.turn_on
                    data: 
                      transition: 0.2
                    target:
                      entity_id: !input light3
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.entpoint_id == 4 }}"
                sequence:
                  - service: light.turn_on
                    data: 
                      transition: 0.2
                    target:
                      entity_id: !input light4
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'off' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.entpoint_id == 1 }}"
                sequence:
                  - service: light.turn_off
                    data: 
                      transition: 0.2
                    target:
                      entity_id: !input light1
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.entpoint_id == 2 }}"
                sequence:
                  - service: light.turn_off
                    metadata: {}
                    data: 
                      transition: 0.2
                    target:
                      entity_id: !input light2
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.entpoint_id == 3 }}"
                sequence:
                  - service: light.turn_off
                    data: 
                      transition: 0.2
                    target:
                      entity_id: !input light3
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.entpoint_id == 4 }}"
                sequence:
                  - service: light.turn_off
                    data: 
                      transition: 0.2
                    target:
                      entity_id: !input light4
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.params.scene_id == 1 }}"
        sequence: !input scene1
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.params.scene_id == 2 }}"
        sequence: !input scene2          
mode: restart
