blueprint:
  name: ROBB SMARRT Wireless Dimmer
  description: Blueprint to control a light with the ROBB SMARRT zigbee dimmer (ROB_200-018-0).
  domain: automation
  input:
    remote:
      name: Dimmer
      description: Robb Smarrt dimmer
      selector:
        device:
          integration: zha
          model: ROB_200-018-0
    light:
      name: Light
      description: Light to be controlled.
      selector:
        entity:
          domain: light
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - service: light.turn_on
            data:
              transition: 0.5
            target:
              entity_id: !input light
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'off' }}"
        sequence:
          - service: light.turn_off
            data:
              transition: 0.5
            target:
              entity_id: !input light
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'move_to_level_with_on_off' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data_template:
              brightness: "{{ trigger.event.data.params.level }}"
              transition: 0.1
mode: single
