blueprint:
  name: Ikea SYMFONISK remote for media player
  description: >
      Blueprint to configure the Ikea SYMFONIKS gen2 zigbee remote to control a media player. 
      Beside all media functions to control the media player the 2 dot buttons have actions voor single press, double press and long press.
  domain: automation
  input:
    remote:
      name: Remote
      description: The remote control.
      selector:
        device:
          integration: zha
          model: SYMFONISK sound remote gen2
          multiple: false
    player:
      name: Media player
      description: Media player to be controlled by this remote
      selector:
        device:
          domain:
          - media_player
          multiple: false
triggers:
  - event_type: zha_event
    event_data:
      device_id: !input remote
    trigger: event
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.cluster_id == 8 }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.params.move_mode == 0 }}"
                sequence:
                  - action: media_player.volume_up
                    data: {}
                    target:
                      device_id: !input player
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.params.move_mode == 1 }}"
                sequence:
                  - action: media_player.volume_down
                    data: {}
                    target:
                      device_id: !input player
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.params.step_mode == 0 }}"
                sequence:
                  - action: media_player.media_next_track
                    target:
                      device_id: !input player
                    data: {}
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.params.step_mode == 1 }}"
                sequence:
                  - action: media_player.media_previous_track
                    target:
                      device_id: !input player
                    data: {}
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.cluster_id == 6 }}"
        sequence:
          - action: media_player.media_play_pause
            target:
              device_id: !input player
            data: {}
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 }}"
        sequence:
          - action: media_player.media_play_pause
            target:
              device_id: !input player
            data: {}
mode: single
